# Generated by Django 3.2.13 on 2022-05-16 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='ユーザー名')),
                ('ZoomURL', models.CharField(max_length=50, verbose_name='Zoom URL')),
                ('Date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('Start', models.TimeField(default=django.utils.timezone.now, verbose_name='開始時間')),
                ('deadline', models.TimeField(default=django.utils.timezone.now, verbose_name='終了時間')),
                ('Status', models.CharField(max_length=50, verbose_name='ステータス')),
            ],
        ),
    ]
