# Generated by Django 3.2.13 on 2022-06-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20220602_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Date',
        ),
    ]
