# Generated by Django 3.2.13 on 2022-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('YO', '予定'), ('JI', '実績'), ('SK', 'スキップ')], default='YO', max_length=2),
        ),
    ]
