# Generated by Django 3.2.13 on 2022-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='eventid',
            field=models.CharField(max_length=26, null=True, verbose_name='イベントID'),
        ),
    ]
