# Generated by Django 3.2.13 on 2022-09-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ZoomURL',
            field=models.URLField(max_length=50, verbose_name='Zoom URL'),
        ),
    ]
