# Generated by Django 3.2.13 on 2022-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_task_zoomurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('予定', '予定'), ('実績', '実績'), ('スキップ', 'スキップ')], default='予定', max_length=16, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True, verbose_name='開始日'),
        ),
    ]
